import localFont from "next/font/local";
import "./globals.css";
import Wrapper from "./wrapper";
import OrderProvider from "@/ContextAPIs/OrderProvider";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/lib/react-query-client";

// Import and set up custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* OrderProvider wraps Wrapper so that the context is available */}
        

        <OrderProvider>
          <Wrapper>
            {children}
          </Wrapper>
        </OrderProvider>
        
      </body>
    </html>
  );
}
